### ISSUE TITLE
bonito/sargo R Android 11

### ISSUE THREAD

**Issue by chirayudesai** [AOSPAlliance/android-prepare-vendor#33]
- [ ] Verified Boot
- [x] Wi-Fi
- [x] Bluetooth
- [x] Camera
- [x] Sound
- [x] Biometrics - fingerprint / face unlock
- [x] Flashlight / torch
- [x] GPS
- [x] Hotspot
- [x] Calls
- [x] Text Messages / SMS
- [x] Mobile data
- [ ] VoLTE
- [x] Wi-Fi Calling
- [ ] Quickly go through logs to make sure there's no obvious crashes / missing libs / etc

**Comment by chirayudesai** [comment]
Also mention:
APV commit, and OS tested with (AOSP/a fork/etc)

**Comment by chirayudesai** [comment]
@gee-one I copied over your results. Forgot to add NFC to the template :/

**Comment by inthewaves** [comment]
Hi, could you also check the permanent timeout for fingerprint unlock and the use of BiometricManager in apps?

I'm having some issues with that using sargo as outlined in https://github.com/GrapheneOS/os_issue_tracker/issues/325 and https://github.com/GrapheneOS/os_issue_tracker/issues/326 (these issues occured to me on both the development branch of GrapheneOS using apv and AOSP android-11.0.0_r1 using the Google blobs, but they did not occur on the stock Google OS)

**Comment by inthewaves** [comment]
@gee-one ^ (didn't realize at first)

**Comment by thestinger** [comment]
This is likely an issue of missing resource overlays. That's something we have not been handling at all beyond a few exceptions.

**Comment by inthewaves** [comment]
> missing resource overlays

This fixes it for sargo: https://github.com/GrapheneOS/device_google_bonito/pull/6

**Comment by chirayudesai** [comment]
This can be closed now, everything works, and this has been running fine for months!
