### ISSUE TITLE
coral/flame R Android 11

### ISSUE THREAD

**Issue by chirayudesai** [AOSPAlliance/android-prepare-vendor#34]
- [x] Verified Boot
- [x] Wi-Fi
- [x] Bluetooth
- [x] Camera
- [x] Sound
- [x] Biometrics - fingerprint / face unlock
- [x] Flashlight / torch
- [x] GPS
- [x] Hotspot
- [x] NFC
- [x] Calls
- [x] Text Messages / SMS
- [x] Mobile data
- [x] VoLTE
- [x] Wi-Fi Calling
- [x] Quickly go through logs to make sure there's no obvious crashes / missing libs / etc

**Comment by chirayudesai** [comment]
Also mention:
APV commit, and OS tested with (AOSP/a fork/etc)

**Comment by anupritaisno1** [comment]
Doesn't work. Boots to a nonfunctional system and audioservice keeps crashing. After about a minute or so the system will soft reboot and this loop continues indefinitely

Tested on grapheneos

**Comment by ghost** [comment]
Works:
Verified boot
WiFi
Bluetooth
Camera
Sound
Flashlight
Hotspot
Calls
SMS
Mobile data

Does not work:
Volte
WiFi calling

I am unable to test a few others on my side

**Comment by ghost** [comment]
Tested on grapheneos

**Comment by ghost** [comment]
Face unlock also works

**Comment by ghost** [comment]
i can turn nfc on but thats all i can test

**Comment by ghost** [comment]
device sensors seem fine

**Comment by ghost** [comment]
gps works and the location readings are accurate

**Comment by ghost** [comment]
no obvious errors in logcat

**Comment by paintedman** [comment]
GrapheneOS 11 RP1A.200720.009. On Pixel 4 XL works:

- [x] Verified Boot
- [x] Wi-Fi
- [x] Bluetooth
- [x] Camera
- [x] Sound
- [x] Flashlight / torch
- [x] GPS
- [x] Hotspot
- [x] NFC - I can successfully check my metro card balance
- [x] Calls
- [x] Text Messages / SMS
- [x] Mobile data
- [x] Quickly go through logs to make sure there's no obvious crashes / missing libs / etc

Problems:

- [ ] Biometrics - fingerprint / face unlock - It looks like the image from the camera is shifted vertically. In 10 it was ok
- [ ] VoLTE - can't test
- [ ] Wi-Fi Calling - can't test

**Comment by ghost** [comment]
Volte and WiFi calling are working fine here

**Comment by ghost** [comment]
WiFi calling and volte were broken due to https://github.com/AOSPAlliance/android-prepare-vendor/issues/36

I added in the missing overlays and now it works
