### ISSUE TITLE
sunfish R Android 11

### ISSUE THREAD

**Issue by chirayudesai** [AOSPAlliance/android-prepare-vendor#35]
- [x] Verified Boot
- [x] Wi-Fi
- [x] Bluetooth
- [x] Camera
- [x] Sound
- [x] Biometrics - fingerprint / face unlock
- [x] Flashlight / torch
- [x] GPS
- [x] Hotspot
- [ ] NFC
- [x] Calls
- [x] Text Messages / SMS
- [x] Mobile data
- [x] VoLTE
- [ ] Wi-Fi Calling
- [ ] Quickly go through logs to make sure there's no obvious crashes / missing libs / etc

**Comment by chirayudesai** [comment]
Also mention:
APV commit, and OS tested with (AOSP/a fork/etc)

**Comment by ghost** [comment]
Tested on grapheneos. It booted

Nothing else has been tested

**Comment by ghost** [comment]
Verified boot is okay

**Comment by losuler** [comment]
- [x] Verified Boot
- [x] Wi-Fi
- [x] Bluetooth
- [x] Camera
- [x] Sound
- [x] Biometrics - fingerprint / face unlock
- [x] Flashlight / torch
- [x] GPS
- [x] Hotspot
- [ ] NFC
- [x] Calls
- [x] Text Messages / SMS
- [x] Mobile data
- [ ] VoLTE
- [ ] Wi-Fi Calling
- [ ] Quickly go through logs to make sure there's no obvious crashes / missing libs / etc

Tested with RattlesnakeOS `v11.0.1` (updated from `v10.0.10`) @dan-v. I haven't noticed anything not working yet, however I'll update this list later today when I get a chance to test further.

I'm not familiar enough with this to understand what exactly I should be looking out for in the logcat messages as they're very noisy, even with `adb logcat "*:E"`. But if there's anything anyone wants me to look out for I can check.

I can confirm the issue with BiometricManager not working https://github.com/AOSPAlliance/android-prepare-vendor/issues/36 (tested with the methods in https://github.com/GrapheneOS/os_issue_tracker/issues/326).

## Update:

I don't think I have VoLTE where I am, so I can't test that. 

Wi-Fi calling isn't showing under `Network & internet > Mobile network`, whereas it does on the Google factory image (on sargo however). But it also isn't showing on Android 10 on RattlesnakeOS (walleye).

I couldn't get NFC to work either, but it doesn't work on walleye on Android 10 either. I was only testing by putting both phones back to back as I don't have any other way I know of to test it.

**Comment by dan-v** [comment]
@losuler can you see if video recording is broken for you? I haven't looked into it yet, but a video call today was unusable (extreme lag) on signal.

**Comment by losuler** [comment]
I wasn't able to reproduce the issue you had with video calls on Signal @dan-v, they were working fine for me both ways. Sadly the latest Google Camera .apk with Gcam-Services-Provider is crashing (the `7.4.x` apk's work fine though, including video), but I assume this is an issue with Gcam-Services-Provider itself (I opened an issue on it at https://github.com/lukaspieper/Gcam-Services-Provider/issues/6).

**Comment by dan-v** [comment]
> I wasn't able to reproduce the issue you had with video calls on Signal @dan-v, they were working fine for me both ways.

I rebooted and the issue went away, but I expect to see it crop up again and will investigate then. When it was in this broken state, taking videos resulted in videos with just a few captured frames (using stock aosp camera and gcam), audio would not record at all (using voice recorder), and a very brief look at logcat showed it spamming excessive log messages.

**Comment by rekesz4** [comment]
- [X] Verified Boot
- [X] Wi-Fi
- [X] Bluetooth
- [X] Camera
- [X] Sound
- [X] Biometrics - fingerprint / face unlock
- [X] Flashlight / torch
- [X] GPS
- [X] Hotspot
- [ ] NFC
- [X] Calls
- [X] Text Messages / SMS
- [X] Mobile data
- [ ] VoLTE
- [ ] Wi-Fi Calling

Tested on GrapheneOS. I couldn't try NFC, VoLTE or Wi-Fi Calling, but everything worked perfectly for me. I also tried Signal video calling and it was smooth for me.

**Comment by chirayudesai** [comment]
This can be closed now, everything works, and this has been running fine for months!
