### ISSUE TITLE
redfin - Pixel 5

### ISSUE THREAD

**Issue by chirayudesai** [AOSPAlliance/android-prepare-vendor#48]
- [x] Verified Boot
- [x] Wi-Fi
- [x] Bluetooth
- [x] Camera
- [x] Sound
- [x] Biometrics - fingerprint / face unlock
- [x] Flashlight / torch
- [x] GPS
- [x] Hotspot
- [x] NFC
- [x] Calls
- [x] Text Messages / SMS
- [x] Mobile data
- [x] VoLTE
- [ ] Wi-Fi Calling
- [ ] Quickly go through logs to make sure there's no obvious crashes / missing libs / etc

**Comment by chirayudesai** [comment]
For: https://github.com/AOSPAlliance/android-prepare-vendor/pull/47

**Comment by hackoder** [comment]
Some testing notes using the changes in #47:
* WiFi: scan, connect, works
* Bluetooth: pair, media playback, file transfer
* Camera: still + video using gcam.
* Sound: playback through speaker, earpiece and BT works as expected
* Biometrics / fingerprint: Setting up/unlocking using FP works
* Flashlight / torch: works
* GPS: Tested using Here WeGO and GPS Test (https://f-droid.org/en/packages/com.android.gpstest.osmdroid/). Got a lock in around 30s.
* Hotspot: works
* NFC: Tried reading an NFC tag, worked as expected.
* Calls: Make/receive call on Telus Canada.
* Text Messages / SMS: Send/receive sms on Telus Canada.
* Mobile data: works

**Comment by chris42** [comment]
Did an aosp build (including microg) with naked configuration out of #47 

- [ ] Verified Boot: not tested
- [x] Wi-Fi: scan, connect, data works
- [x] Bluetooth: scan, pair, connect works
- [x] Camera: OpenCamera + GoogleCamera works
- [x] Sound: works
- [x] Biometrics - fingerprint / face unlock: fingerprint works
- [x] Flashlight / torch: works
- [x] GPS: works
- [x] Hotspot: 2,4+5Ghz works for mobile data; seems to also allow tethering my Wifi connection. Didn't know it could do that.
- [x] NFC: works reading NFC tag
- [x] Calls: works 
- [x] Text Messages / SMS: works
- [x] Mobile data: works
- [ ] VoLTE: not tested
- [ ] Wi-Fi Calling: not tested

Still have to check logs. First look did not have any repeating issues, however have to check boot and library errors.
I put this now on my daily driver and will see if any issues come up.

Regarding microg: Seems to work as expected, but longer use will show.

**Comment by chris42** [comment]
@sdh4
On following libs I get errors. 
libdiag_system.so is available in the factory image system_ext, hence simple add to the libs should solve this.

The other two, I could not find. It seems to be connected to the camera, however I have little knowledge with that.

```
01-01 11:27:18.800  2437  2437 E ims_media_jni: Error loading library lib-imsvt.so: dlopen failed: library "libdiag_system.so" not found: needed by /system_ext/lib64/lib-imsvt.so in namespace classloader-namespace-shared

01-01 11:27:20.282   878   878 E GAF     : TuningManager: gaf_tuning_manager.cc: 67: Load:/vendor/lib64/com.google.af.tuning.imx355.so: dlopen failed: library "/vendor/lib64/com.google.af.tuning.imx355.so" not found

01-01 11:27:20.282   878   878 E GAF     : TuningManager: gaf_tuning_manager.cc: 67: Load:/vendor/lib64/com.google.af.tuning.imx481.so: dlopen failed: library "/vendor/lib64/com.google.af.tuning.imx481.so" not found
```

**Comment by sdh4** [comment]
I added libdiag_system to #47 (commit ab3d331). I have not tested this change so far.

The imx355 and imx481 are probably parallel libraries to the  com.google.af.tuning.imx363.so that is included in /vendor. 
Supposedly (https://twitter.com/MishaalRahman/status/1297417288333905920?s=20) the imx355, imx363, and imx481 are the three camera sensors in the Pixel 5. Presumably the 355 and 481 didn't need any special autofocus tuning (or something like that) or Google would have included the libraries.

**Comment by chris42** [comment]
Ok, might be, that the different cameras are not tuned, however we are missing all tuning libraries? O_o
In the vendor files there are (of which are none in the current config):
in vendor/lib64
```
com.google.af.tuning.imx363.so
```
and in vendor/lib64/camera
```
com.google.gabc.tuning.imx355.so
com.google.gabc.tuning.imx363.so
com.google.gabc.tuning.imx481.so
com.google.ghawb.tuning.imx355.so
com.google.ghawb.tuning.imx363.so
com.google.ghawb.tuning.imx481.so
```
I will read up on the pixel cameras and see if I can make sense out of this "gabc, ghawb" and distribution on different sensors.

I tested the libdiag_system with a rough build and the error was gone, will check for any follow up errors today or tomorrow.

**Comment by chris42** [comment]
So i checked on the camera setup out of the tweet and searched the other libraries.
- main wide 12.2MP IMX363
- main ultrawide 16MP IMX481
- selfie 8MP IMX355

So it makes sense, what you said, that only the primary main camera IX363 has autofocus.
The gabc and ghawb seem to be noise reduction and white balancing libraries for each camera. All of them are included in the factory image and in the driver files. Hence I guess all of them should go in naked?

EDIT: Of course the files are included. I am always getting confused, that the config changes mid way from include to exclude ;-)

**Comment by chris42** [comment]
Having a build with libdiag_system.so, that dlopen error is gone and device seems to behave.
Besides the af.tuning library errors, I only have one dlopen error left in the logs:
```
01-02 23:29:56.590  5430  5430 E a2dp_vendor_ldac_decoder: A2DP_VendorLoadDecoderLdac: cannot open LDAC decoder library libldacBT_bco.so: dlopen failed: library "libldacBT_bco.so" not found
```

ImsService seems to be in trouble and repeatedly gets "no ImsService available":
```
01-02 23:40:42.297  2385  2385 W Telephony: registerMmTelCapabilityCallback: registration failed, no ImsService available. Exception: CapabilityCallbackManager - MmTelFeature binder is dead. (code: 1)
01-02 23:40:42.298  2385  2385 E MmTelFeatureConnection [0]: ImsRegistrationCallbackAdapter: ImsRegistration is null
01-02 23:40:42.299  2061  2061 D KeyguardUpdateMonitor: handleSimStateChange(subId=-1, slotId=0, state=0)
01-02 23:40:42.299  2061  2061 W KeyguardUpdateMonitor: invalid subId in handleSimStateChange()
01-02 23:40:42.299  2385  2385 W Telephony: registerImsRegistrationCallback: registration failed, no ImsService available. Exception: ImsRegistrationCallbackAdapter: MmTelFeature isnot available! (code: 1)
```
Will need to search where that craps out...

**Comment by sdh4** [comment]
@chris42  -- libldacBT_bco.so does not seem to exist even in the Google images, so presumably it is unnecessary. 

With respect to your IMS messages, on mine about a second after the messages you quote, the ImsService seems to start up OK.

**Comment by sdh4** [comment]
The only remaining problem I notice are:
- Touching events or free spaces in the built-in calendar app doesn't do anything. This is probably just general AOSP brokeness. 
- It's not clear both rear-facing cameras are working. Camera apps only seem to show two cameras (one front, one rear) and all the test pictures I have tried seem to use the sensor that is one the right hand side when using the display. Logcat messages imply that the phone is trying to treat both rear cameras as a single logical camera, but obviously if that is working properly some pictures would use each sensor. 
```
01-03 22:18:53.856   877   877 D GCH_CameraVendorModule: PrintCamerasInformation: Enumerated cameras:
01-03 22:18:53.857   877   877 D GCH_CameraVendorModule: PrintCamerasInformation: -------------------------------------------------
01-03 22:18:53.857   877   877 D GCH_CameraVendorModule: PrintCamerasInformation: |Public|Internal	 |Physical  |Camera
01-03 22:18:53.857   877   877 D GCH_CameraVendorModule: PrintCamerasInformation: |ID	 |ID	 |Visible|Public IDs|Type
01-03 22:18:53.857   877   877 D GCH_CameraVendorModule: PrintCamerasInformation: |------------------------------------------------
01-03 22:18:53.857   877   877 D GCH_CameraVendorModule: PrintCamerasInformation: |0	 |3	 |YES	 |2, 3      | Rear Logical
01-03 22:18:53.857   877   877 D GCH_CameraVendorModule: PrintCamerasInformation: |1	 |1	 |YES	 |          | Front
01-03 22:18:53.857   877   877 D GCH_CameraVendorModule: PrintCamerasInformation: |2	 |0	 |NO	 |          | Rear-Wide
01-03 22:18:53.857   877   877 D GCH_CameraVendorModule: PrintCamerasInformation: |3	 |2	 |NO	 |          | Rear-UltraWide
```

**Comment by chris42** [comment]
> @chris42 -- libldacBT_bco.so does not seem to exist even in the Google images, so presumably it is unnecessary.
> 
> With respect to your IMS messages, on mine about a second after the messages you quote, the ImsService seems to start up OK.

For me always hard to tell, what is needed and what not.

The IMS exceptions caught my attention as I had them 15-20 times in the log, which seemed a bit excessive.

**Comment by chris42** [comment]
@chirayudesai 
As I saw the carrier_list conversion in the commits, I wondered that CarrierIdProvider is still looking for the .pb:

`01-04 21:34:46.552  2418  2418 E CarrierIdProvider: read carrier list from ota pb failure: java.io.FileNotFoundException: /data/misc/carrierid/carrier_list.pb: open failed: ENOENT (No such file or directory)`

Might be a cosmetic and irrelevant...

**Comment by chirayudesai** [comment]
Thanks for testing everyone, I updated the list in the description, and added one more item I tested (VoLTE)

**Comment by chirayudesai** [comment]
> The only remaining problem I notice are:
> 
> * Touching events or free spaces in the built-in calendar app doesn't do anything. This is probably just general AOSP brokeness.

Yeah...
> * It's not clear both rear-facing cameras are working. Camera apps only seem to show two cameras (one front, one rear) and all the test pictures I have tried seem to use the sensor that is one the right hand side when using the display. Logcat messages imply that the phone is trying to treat both rear cameras as a single logical camera, but obviously if that is working properly some pictures would use each sensor.
> 

I'd check Google Camera for this, can grab 7.6 from the stock factory images. It will need some sort of GMS, either the full thing or microG or a stub, it should work then.

**Comment by chris42** [comment]
`I'd check Google Camera for this, can grab 7.6 from the stock factory images. It will need some sort of GMS, either the full thing or microG or a stub, it should work then.`

I actually tested it on a AOSP with microg and arnova GCAM beta, I observe the same, that only one camera is used (I cover the other to test). It seems that not all functionality of the camera is working. E.g. night mode is different on a build with drivers and binaries in comparison to this build.

**Comment by chirayudesai** [comment]
The two cameras on these phones are
1) Primary 12.2MP wide lens, the outer camera
2) Ultrawide 16MP, the inner camera

Both work fine here with the official Google Camera (no modded apk)

If I cover the first / outermost lens, 1x and 2x won't work.
If I cover the second / inner lens, .6x won't work.

**Comment by arnodorian-r** [comment]
@chirayudesai 
02-10 23:47:40.172  2359  2359 E MmTelFeatureConnection [0]: ImsRegistrationCallbackAdapter: ImsRegistration is null
02-10 23:47:40.172  2359  2359 W Telephony: registerImsRegistrationCallback: registration failed, no ImsService available. Exception: ImsRegistrationCallbackAdapter: MmTelFeature isnot available! (code: 1)
02-10 23:47:40.172  2359  2359 I Telephony: TelecomAccountRegistry: setupAccounts: Phone with subscription id -1
02-10 23:47:40.172  2359  2359 D Telephony: TelecomAccountRegistry: setupAccounts: skipping invalid subid -1

can i know how you got this solved?

**Comment by chirayudesai** [comment]
@arnodorian-r IMS has always worked fine here (even on plain AOSP without any other changes), maybe retry with the latest changes?

This can be closed now, everything works, and this has been running fine for months!
