### ISSUE TITLE
barbet: Pixel 5a

### ISSUE THREAD

**Issue by chirayudesai** [AOSPAlliance/android-prepare-vendor#72]
- [x] Verified Boot
- [x] Wi-Fi
- [x] Bluetooth
- [x] Camera
- [x] Sound
- [x] Biometrics - fingerprint / face unlock
- [x] Flashlight / torch
- [x] GPS
- [x] Hotspot
- [x] NFC
- [x] Calls
- [x] Text Messages / SMS
- [x] Mobile data
- [x] VoLTE
- [x] Wi-Fi Calling
- [x] Quickly go through logs to make sure there's no obvious crashes / missing libs / etc

**Comment by chirayudesai** [comment]
Should mostly be fine given it's just one more redbull but doesn't hurt.

**Comment by chirayudesai** [comment]
https://github.com/AOSPAlliance/android-prepare-vendor/pull/71

**Comment by trondd555** [comment]
Tested good so far:
Verified boot
WiFi
Bluetooth - probably, connected to laptop, don't own any BT peripherals
Camera (front and rear)
Sound
Fingerprint unlock
Flashlight

I'll test calls, etc when I get my sim moved over

**Comment by trondd555** [comment]
Also verified:
GPS
Calls
Text
Mobile Data

I can't test hotspot, NFC, VoLTE or Wi-Fi calling.

Searched through the build log for "fatal" and "error" and only found file names and compiler parameters.  If there is anything else to look for, let me know.

**Comment by chirayudesai** [comment]
@trondd555 thank you so much for testing!

That should cover it, I can test the rest once I get mine but for now this should do.
