### ISSUE TITLE
GrapheneOS android-prepare-vendor Android 12 port must not be used by CalyxOS

### ISSUE THREAD

**Issue by thestinger** [AOSPAlliance/android-prepare-vendor#78]
You aren't permitted to use this code and it has not been made available under an open source license permitting you to use it as we did with our past code. Drop all of our Android 12 porting work from your repository and anyone that has looked at it shouldn't be pretending they can make a new implementation that's not derived from our work.

**Comment by thestinger** [comment]
There has never been an explicit license in APV but rather an implicit one and we explicitly revoked permission for CalyxOS to use our code going forward. If you'd like we can explicit publish what we've already said before about this as part of our repository. Our continuation of APV is not available for use by Calyx employees, contractors, contributors or community members. The past collaboration between the projects is over and you shouldn't be using our work anymore.

**Comment by chirayudesai** [comment]
Branch `android12` has been deleted.
