### ISSUE TITLE
Repository data is LICENSE free, use it as you want at your own risk.

### ISSUE THREAD

**Issue by gpetersson** [AOSPAlliance/android-prepare-vendor#79]
From your own README:

> Repository data is LICENSE free, use it as you want at your own risk.

You cannot retroactively revoke permission you already gave to people. Only if this sentence were removed, then without a LICENSE the content becomes proprietary from that point forward, and permission would be needed... but the repo state as it is while this sentence still exists, makes it free game for everyone.

**Comment by FecalFornicator** [comment]
What a bunch of clowns these people are.  This is a childish (and frankly futile) attempt to stifle development of CalyxOS 🤡🤡🤡
